services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TRITUM\Turnstile\:
        resource: '../Classes/*'

    TRITUM\Turnstile\Service\ConfigurationService:
        public: true

